/*
Copyright 2023 Sangfor Technologies Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"arsenal/models"
)

// DeleteFaultsIDOKCode is the HTTP code returned for type DeleteFaultsIDOK
const DeleteFaultsIDOKCode int = 200

/*
DeleteFaultsIDOK Response successfully

swagger:response deleteFaultsIdOK
*/
type DeleteFaultsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Infos200Response `json:"body,omitempty"`
}

// NewDeleteFaultsIDOK creates DeleteFaultsIDOK with default headers values
func NewDeleteFaultsIDOK() *DeleteFaultsIDOK {

	return &DeleteFaultsIDOK{}
}

// WithPayload adds the payload to the delete faults Id o k response
func (o *DeleteFaultsIDOK) WithPayload(payload *models.Infos200Response) *DeleteFaultsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete faults Id o k response
func (o *DeleteFaultsIDOK) SetPayload(payload *models.Infos200Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteFaultsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteFaultsIDNotFoundCode is the HTTP code returned for type DeleteFaultsIDNotFound
const DeleteFaultsIDNotFoundCode int = 404

/*
DeleteFaultsIDNotFound No fault's information found

swagger:response deleteFaultsIdNotFound
*/
type DeleteFaultsIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error404Response `json:"body,omitempty"`
}

// NewDeleteFaultsIDNotFound creates DeleteFaultsIDNotFound with default headers values
func NewDeleteFaultsIDNotFound() *DeleteFaultsIDNotFound {

	return &DeleteFaultsIDNotFound{}
}

// WithPayload adds the payload to the delete faults Id not found response
func (o *DeleteFaultsIDNotFound) WithPayload(payload *models.Error404Response) *DeleteFaultsIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete faults Id not found response
func (o *DeleteFaultsIDNotFound) SetPayload(payload *models.Error404Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteFaultsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteFaultsIDInternalServerErrorCode is the HTTP code returned for type DeleteFaultsIDInternalServerError
const DeleteFaultsIDInternalServerErrorCode int = 500

/*
DeleteFaultsIDInternalServerError Server error while processing the request

swagger:response deleteFaultsIdInternalServerError
*/
type DeleteFaultsIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error500Response `json:"body,omitempty"`
}

// NewDeleteFaultsIDInternalServerError creates DeleteFaultsIDInternalServerError with default headers values
func NewDeleteFaultsIDInternalServerError() *DeleteFaultsIDInternalServerError {

	return &DeleteFaultsIDInternalServerError{}
}

// WithPayload adds the payload to the delete faults Id internal server error response
func (o *DeleteFaultsIDInternalServerError) WithPayload(payload *models.Error500Response) *DeleteFaultsIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete faults Id internal server error response
func (o *DeleteFaultsIDInternalServerError) SetPayload(payload *models.Error500Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteFaultsIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
